use_frameworks!

platform :ios, '8.0'

target 'GGBasePageModel_Example' do
  pod 'GGBasePageModel', :path => '../'

  target 'GGBasePageModel_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
